### PR TITLE
Enhancement: Added restored and minimized events

### PR DESCRIPTION
**Pull request by ayoubboulila**
Enhancement:
Added restored and minimized Fired events to enhance the behavior of portlet to portlet communication with third parties integrated platforms (AngularJS, Dojo for example) as a result this will give more flexibility handling it and enable refreshing/rendering angularJs Apps on minimize and restore events.

### CODE REVIEW

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by sammonsjl** [comment]
In an effort to clean up our liferay-portal repository we are currently going through all old pull requests and closing them.  If you feel this change is still necessary please reopen the pull request and we can assist you.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
