### PR TITLE
LPS-98452 - Change log level from DEBUG to WARN

### PR DESCRIPTION
**Pull request by amusarra**
Change the log level from debug to waring when the DuplicateLockException exception occurs. It is very useful to see this condition immediately on the log file.

### CODE REVIEW

**Comment by sammonsjl** [comment]
Hi @amusarra thank you for the contribution!

/Cc @holatuwol @jonathanmccann @SamZiemer @AngeloJ can one you take a look at this one?

**Comment by holatuwol** [comment]
I think there are Liferay integration tests that will fail if there is a WARN level message in the logs, and since this is essentially a race condition, WARN seems like it could cause headaches down then line.

Since duplicate locks are expected, and we're handling the condition, it makes sense if it's INFO instead of DEBUG level, and then add `src/main/resources/META-INF/module-log4j.xml` to the module to increase the log level for BackgroundTaskMessageListener to INFO.

@amusarra : To confirm, would having the message be at INFO, if that were set as the default for that logger, still satisfy your needs for [LPS-98452](https://issues.liferay.com/browse/LPS-98452)? If so, would you be able to make that change, or would you prefer that someone from the reviewer team do so?

**Comment by holatuwol** [comment]
In case it helps, `module-log4j.xml` is documented in the developer guide:

https://portal.liferay.dev/docs/7-0/tutorials/-/knowledge_base/t/adjusting-module-logging

**Comment by amusarra** [comment]
Hi @holatuwol 
Tomorrow I will make the change by bringing the log level to INFO and adding the file `resources/META-INF/module-log4j.xml` with the following content:

```
<?xml version="1.0"?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">
    <category name="com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener">
        <priority value="INFO" />
    </category>
</log4j:configuration>
```

How do we go on? Do I close this pull request and open another with the new changes?

**Comment by holatuwol** [comment]
@amusarra : If you push to your branch, it should update this pull request.

**Comment by amusarra** [comment]
Hi @holatuwol 
Push performed.

**Comment by amusarra** [comment]
Hi @holatuwol 
Let me know if everything is ok.

**Comment by holatuwol** [comment]
@amusarra : Ran source formatter and squashed the commits. Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1814

**Comment by holatuwol** [comment]
ci:close

**Pull request closed without merging**
