### PR TITLE
LPS-204124 Remove unused @Reference variables in ScheduledPublishMessageListener.java

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-204124](https://liferay.atlassian.net/browse/LPS-204124)

[LPS-204124]: https://liferay.atlassian.net/browse/LPS-204124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
@gislayne-vitorino can you send this to @liferay-publications?

**Pull request closed without merging**
