### PR TITLE
LPS-120795 minimize logging

### PR DESCRIPTION
**Pull request by joshuacords**
Hello @wcao20170619,

Authors: @wcao20170619 @joshuacords 
Reviewer: @joshuacords 

https://issues.liferay.com/browse/LPS-120795

A few changes:
- I've improved the wording of the Warning for the Sidecar with Russell's help. Also, we still want this warning to appear if the user is using embedded mode.
- I've turned off the ES warnings with the log4j2 changes, to be refined by later tickets.

If you're okay with these changes you can hand them off to Joshua Chong.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by wcao20170619** [comment]
@joshuacords thanks for the correction.

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:stop

**Comment by joshchong** [comment]
This was sent to the wrong repo, resent here: https://github.com/liferay-search/liferay-portal/pull/40

**Comment by joshuacords** [comment]
Whoops, thanks @joshchong

**Pull request closed without merging**
