### PR TITLE
LPS-68297 Update the com-liferay-journal repository

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by jhendley** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero can you resend? The regeneration should not up the service.properties like that without a real database change. I'm going to remove the auto modification of that file going forward.

**Comment by brianchandotcom** [comment]
@Ithildir can you change ServiceBuilder to default to NOT generate service.properties? At least for us. Thx.

**Pull request closed without merging**
