### PR TITLE
COMMERCE-9780 We only need to get the resultsMap once

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-9780

@andrea-ale-sbarra , @luca-pellizzon

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Review by luca-pellizzon — APPROVED** [review]

**Comment by baharturk** [comment]
ci:forward

**Comment by baharturk** [comment]
Hi @brianikim, I tested this PR and left a QA passed comment on Jira ticket. To be able to forward this PR, it needs to be sent to liferay-commerce instead of liferay. Could you resolve this issue and forward the PR, please? Thanks!

**Comment by brianikim** [comment]
hey @baharturk , sorry about that: https://github.com/liferay-commerce/liferay-portal/pull/2948

**Pull request closed without merging**
