### PR TITLE
LPS-67973 Update the com-liferay-journal repository

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:merge

**Comment by stsquared99** [comment]
ci:merge

**Comment by stsquared99** [comment]
ci:merge:force

**Comment by stsquared99** [comment]
ci:merge

**Comment by stsquared99** [comment]
ci:merge:force

**Comment by brianchandotcom** [comment]
ci:merge:force

**Comment by brianchandotcom** [comment]
@juliocamarero This is in upstream now.

Thx @stsquared99 

I'm going to work with @Ithildir to work out a few more kinks like:

1.) Fixing the .version-override-* files that were necessary before but not anymore.

2.) Coming up with a standard README format.

Thx

**Pull request closed without merging**
