### PR TITLE
Update dynamic-data-mapping subrepo

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 @marcellustavares

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@vicnate5, could you help us on this?

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
This is a known issue on the PR tester right now :(

https://loop.liferay.com/home/-/loop/feed/5348796

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
lpkg-override-jdk8 hung again..

**Comment by marcellustavares** [comment]
ci:close

**Pull request closed without merging**
