### PR TITLE
Update util-taglib/src/com/liferay/taglib/ui/InputPermissionsTag.java

### PR DESCRIPTION
**Pull request by fsforna**
Dear Liferay Support,
has you requested we have done our contribution to solve this bug:

http://issues.liferay.com/browse/LPS-30219

I hope that it may be useful for you.

Best Regards,
Francesco.

### CODE REVIEW

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by sammonsjl** [comment]
In an effort to clean up our liferay-portal repository we are currently going through all old pull requests and closing them.  If you feel this change is still necessary please reopen the pull request and we can assist you.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
