### PR TITLE
LPS-121077 Added use of start and end parameters to the AssetCategoryServiceImpl.search(long[] groupIds, String name, long[] vocabularyIds, int start, int end) method

### PR DESCRIPTION
**Pull request by dbagrey**
Added use of start and end parameters to the AssetCategoryServiceImpl.search(long[] groupIds, String name, long[] vocabularyIds, int start, int end) method
https://issues.liferay.com/browse/LPS-121077

### CODE REVIEW

**Comment by dbagrey** [comment]
ci:forward

**Comment by sammonsjl** [comment]
Hi @dbagrey, thank you for the contribution!  You can follow the progress here: https://github.com/liferay-echo/liferay-portal/pull/2697

**Comment by sammonsjl** [comment]
Hi @dbagrey fixed in: https://github.com/brianchandotcom/liferay-portal/pull/95289

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
