### PR TITLE
Offline sites concept LPS-31260

### PR DESCRIPTION
**Pull request by jiriKadlec**
How to use it:

After starting up Liferay and signing in, create some page structure and add some web content with images (i.e. create two pages "/home" and "/news" and add Web content display portlet with some article to them).

When the desired web structure is created, go to Control Panel to "Site Pages" and follow these steps:
change the theme for the whole layout set to "App cache sample theme" (this is a lightweight theme, which also adds manifest attribute to the html tag)
in the "Offline access" section:
check "Allow offline access"
add following folders in "Folders with resources to be cached":
/html/themes/app_cache_sample_theme/css/
/html/themes/app_cache_sample_theme/js/
/html/themes/app_cache_sample_theme/images/jqm/
While adding the folders, make sure folder location is correct. Theme is shiped with Liferay, so it is in the ROOT folder in webapps (add "ROOT/" to the path like this: .../webapps/ROOT/html/themes/app_cache_sample_theme/...).
Save the changes

After that, offline access is set up. Log out (or use another browser) and go to one of the pages (i.e. "/home"). Page will load as ususal and after a short while it will also be downloaded to the cache (can be checked in the console of the browser).
You can now shutdown the server.
When you access the same page again (i.e. "/home") from the same browser, it will load just fine. Even the second page (which has not been displayed yet) will load fine - try to go to the second page (i.e. "/news").

### CODE REVIEW

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by sammonsjl** [comment]
In an effort to clean up our liferay-portal repository we are currently going through all old pull requests and closing them.  If you feel this change is still necessary please reopen the pull request and we can assist you.

**Comment by sammonsjl** [comment]
ci:close

**Comment by sammonsjl** [comment]
ci:close

**Comment by sammonsjl** [comment]
ci:close

**Comment by holatuwol** [comment]
ci:stop

**Comment by sammonsjl** [comment]
ci:close

**Comment by sammonsjl** [comment]
ci:close

**Comment by sammonsjl** [comment]
ci:close

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
