### PR TITLE
Fix bug when Language value contains ' or ".

### PR DESCRIPTION
**Pull request by guli**
Fix bug when Language value contains ' or ".

### CODE REVIEW

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by sammonsjl** [comment]
In an effort to clean up our liferay-portal repository we are currently going through all old pull requests and closing them.  If you feel this change is still necessary please reopen the pull request and we can assist you.

**Comment by sammonsjl** [comment]
ci:close

**Comment by holatuwol** [comment]
ci:close

**Pull request closed without merging**
