### PR TITLE
Update Language_de.properties

### PR DESCRIPTION
**Pull request by crabel**
The correct name of the country is "Bosnien und Herzegowina" in German. See e.g. Wikipedia:
https://de.wikipedia.org/wiki/Bosnien_und_Herzegowina

### CODE REVIEW

**Comment by sammonsjl** [comment]
Hi @crabel thank you for the contribution!

/Cc @holatuwol @jonathanmccann @SamZiemer @AngeloJ can one you take a look at this one?

**Comment by holatuwol** [comment]
@sammonsjl : We aren't able to accept contributions to Language.properties files through GitHub, because it will all get overwritten with whatever is stored on CrowdIn.

@wanderlast : @crabel has provided a recommended change for the name of a country (as it would be read in German) and they've linked German Wikipedia article as a source. Could that be handled through whatever CrowdIn workflow we have for customer-requested translations, or has that process not yet been finalized?

**Comment by wanderlast** [comment]
Hi @crabel,
Thanks for letting us know about this! I've added the fix to our localization workflow so the change should be reflected soon once everything's merged in.

**Comment by holatuwol** [comment]
@crabel : @wanderlast submitted the translation to CrowdIn, and it should be updated in master with the next sync (not sure when the sync is scheduled, @sammonsjl might have more insight).

https://translate.liferay.com/translate/liferay-portal/15598/en-de#359414

If you'd like to submit additional translation suggestions, we learned that the official process for community members is to ask to join as a community translator, which is documented on portal.liferay.dev under Participate.

https://portal.liferay.dev/participate/translate/overview
https://portal.liferay.dev/participate/translate/translate-to-your-language

**Comment by sammonsjl** [comment]
I'm going to assume this one is taken care of now. Please reopen if that is not the case.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
