### PR TITLE
Remove extra period in the default repos property

### PR DESCRIPTION
**Pull request by garyttierney**
The property named below:

    liferay.workspace.default.repositories.enabled

Was being incorrectly looked up as follows:

    liferay.workspace..default.repositories.enabled

Due to a stray character in the RootProjectConfigurator constructor.

Signed-off-by: Gary Tierney <gary.tierney@fastmail.com>

### CODE REVIEW

**Comment by sammonsjl** [comment]
Hi @garyttierney thank you for the contribution!

/Cc @holatuwol @jonathanmccann @SamZiemer @AngeloJ can one you take a look at this one?

**Comment by holatuwol** [comment]
@sammonsjl : I wasn't able to find an associated LPS to track the bug, so I created one ([LPS-99442](https://issues.liferay.com/browse/LPS-99442)). However, I wasn't able to locate Gary as a user in JIRA to assign the ticket to confirm acceptance of the Contributor's Agreement.

@garyttierney : Assuming you haven't done so already, when you have time, can you read through the [Contributor's Agreement](https://www.liferay.com/legal/contributors-agreement)?

If you agree to those terms, would you be able to create an account in JIRA (if you have not already done so), assign [LPS-99442](https://issues.liferay.com/browse/LPS-99442) to yourself, and use the JIRA workflow to indicate that you've accepted the conditions associated with contributing a solution?

If you don't agree to those terms, let us know as well.

**Comment by garyttierney** [comment]
Sure, that's no problem. The CLA looks pretty sound, I'll create a JIRA account and get that accepted tomorrow morning.

**Comment by garyttierney** [comment]
@holatuwol I don't think I'm able to assign the issue to myself, but I've contributed a solution using the JIRA workflow and accepted the CLA.

**Comment by holatuwol** [comment]
https://github.com/petershin/liferay-portal/pull/624

**Comment by holatuwol** [comment]
ci:close

**Pull request closed without merging**
