### PR TITLE
LPS-98250 Update alloyeditor to v2.0.8

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-98250

This pull updates alloyeditor to v2.0.8 in order to fix LPS-98250. I was able to see that this change resolves this issue. Let me know if there are any questions or comments about this.

Thank you.

### CODE REVIEW

**Comment by wincent** [comment]
@fortunatomaldonado: see https://github.com/brianchandotcom/liferay-portal/pull/75981

**Comment by fortunatomaldonado** [comment]
@wincent, thank you for the help with this!
In the future, should I send PRs related to AE to you?

**Comment by wincent** [comment]
Not if the future is the next 10 days, because I won't be online. 😂

@julien has done most (or all?) of the AlloyEditor updates in liferay-portal lately, but he is on PTO right now, so today when I cut the v2.0.8 release I sent the update PR to Brian right after, because I think that's what Julien has been doing.

**Comment by fortunatomaldonado** [comment]
Haha sounds good!

Thanks again for this and I will start backporting 7.1 and 7.0.

**Pull request closed without merging**
