### PR TITLE
Update setenv.bat

### PR DESCRIPTION
**Pull request by olafk**
This file referenced jre1.6.0_20 for a long time, containing dead code for a long time. Since it also doesn't have Windows line-ending-encoding, editing it in Notepad is quite hard. It's best to keep this file with a single line in the default deployment. As the deleted code was ineffective anyways, I didn't bother opening an issue - hope this is sufficient.

### CODE REVIEW

**Comment by jpince** [comment]
@shuyangzhou what do you think?

**Comment by sammonsjl** [comment]
Hey @olafk I'm going through and cleaning up old pull requests.  Is this one still relevant for the latest master?

**Comment by olafk** [comment]
Thank you, for taking care of old pullrequests, @sammonsjl .
In master, the file (still) references @java.version@, a placeholder that was resolved to 1.6_20 in DXP 7.1 GA1 - which continues to be utterly useless. If I understand correctly, Liferay wouldn't even run with a JRE, only with a JDK, but still not at all with 1.6. 
While there's a conflict now (due to changes in the CATALINA_OPTS line), I'll stand by my request to remove the whole utter useless JRE-carfuffle from the beginning of the file. It's been superfluous for years. Plus, nobody who has downloaded the Tomcat bundle has continued to install a JRE in a "win" subdirectory of the downloaded bundle ever. If Liferay delivered it once upon a time, it was probably around the release time of 1.6_20, around May 2010 if I found the correct release notes.

**Comment by holatuwol** [comment]
> If Liferay delivered it once upon a time, it was probably around the release time of 1.6_20, around May 2010 if I found the correct release notes.

Right, including an embedded JRE is part of the distribution bundle creation process, if the distribution is generated on a Windows machine, which hasn't been the case in a very long time. The feature was first included in [LPS-7714](https://issues.liferay.com/browse/LPS-7714) (March 2010) and the default value for the value in release.properties was last updated in [LPS-11318](https://issues.liferay.com/browse/LPS-11318) (July 2010).

If we move forward with removing it from setenv.bat, we would want to also update the lines in build-dist.xml that reference it to copy without doing any replacement.

https://github.com/liferay/liferay-portal-ee/blob/7.1.0-ga1/build-dist.xml#L2157-L2178

**Comment by holatuwol** [comment]
The last release where we included an embedded JRE was 6.2.4 GA5.

https://releases.liferay.com/portal/6.2.4-ga5/
https://releases.liferay.com/portal/6.2.5-ga6/

I've opened [LPS-88554](https://issues.liferay.com/browse/LPS-88554) to document the issue.

**Comment by holatuwol** [comment]
https://github.com/SamZiemer/liferay-portal/pull/530

**Comment by holatuwol** [comment]
ci:close

**Pull request closed without merging**
