### PR TITLE
Update GroupLocalServiceImpl.java

### PR DESCRIPTION
**Pull request by lequangtu**
LPS-41359 Created group for Site/Page Template has name = classPk instead of Site/Page Template's name. The group's name is only update when  updating Site/Page Template. In my opninion, the group's name is setted to classPk only in case of creation group for User Personal Site or in case of the name is null.

### CODE REVIEW

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by sammonsjl** [comment]
In an effort to clean up our liferay-portal repository we are currently going through all old pull requests and closing them.  If you feel this change is still necessary please reopen the pull request and we can assist you.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
