### PR TITLE
LPS-96247 Migrate away from deprecated SourceSetOutput.getClassesDir

### PR DESCRIPTION
**Pull request by jrodbx**
It's been removed in Gradle 5.x

https://issues.liferay.com/browse/LPS-96247

### CODE REVIEW

**Comment by sammonsjl** [comment]
Hi @jrodbx thank you for the contribution!

/Cc @holatuwol @jonathanmccann @SamZiemer @AngeloJ can one you take a look at this one?  I know we are starting to take some beginning steps to move to Gradle 5.x so maybe this can help.

**Comment by holatuwol** [comment]
@jrodbx: I ran a script to check if there were any other places we called `getClassesDir()`, which (based on my understanding of your comments thus far) should all be removed:

```bash
git ls-files modules/sdk/ | grep -F .java | xargs grep -Fl SourceSetOutput | \
	xargs grep -Fn 'sourceSetOutput.getClassesDir()' | cut -d':' -f 1,2 |
	awk 'BEGIN { FS = ":" } ; { print "* [" $1 "#L" $2 "](https://github.com/liferay/liferay-portal/tree/master/" $1 "#L" $2 ")" }'
```

That gives us four additional cases where we need to apply this new pattern:

* [modules/sdk/gradle-plugins-defaults/src/main/java/com/liferay/gradle/plugins/defaults/LiferayOSGiDefaultsPlugin.java#L2794](https://github.com/liferay/liferay-portal/tree/master/modules/sdk/gradle-plugins-defaults/src/main/java/com/liferay/gradle/plugins/defaults/LiferayOSGiDefaultsPlugin.java#L2794)
* [modules/sdk/gradle-plugins-node/src/main/java/com/liferay/gradle/plugins/node/NodePlugin.java#L608](https://github.com/liferay/liferay-portal/tree/master/modules/sdk/gradle-plugins-node/src/main/java/com/liferay/gradle/plugins/node/NodePlugin.java#L608)
* [modules/sdk/gradle-plugins-test-integration/src/main/java/com/liferay/gradle/plugins/test/integration/TestIntegrationBasePlugin.java#L206](https://github.com/liferay/liferay-portal/tree/master/modules/sdk/gradle-plugins-test-integration/src/main/java/com/liferay/gradle/plugins/test/integration/TestIntegrationBasePlugin.java#L206)
* [modules/sdk/gradle-plugins/src/main/java/com/liferay/gradle/plugins/internal/IdeaDefaultsPlugin.java#L92](https://github.com/liferay/liferay-portal/tree/master/modules/sdk/gradle-plugins/src/main/java/com/liferay/gradle/plugins/internal/IdeaDefaultsPlugin.java#L92)

Since you contributed the first fix, did you want to apply your changes to those files as well? Or would you prefer that the reviewers take care of that?

**Comment by jrodbx** [comment]
@holatuwol and others: I've applied the changes to the other call sites as well.  PTAL.

**Comment by holatuwol** [comment]
https://github.com/petershin/liferay-portal/pull/545

**Comment by jrodbx** [comment]
Hmm, the build failure appears unrelated to my change: https://github.com/petershin/liferay-portal/pull/545#issuecomment-503289626

**Comment by jrodbx** [comment]
Build failure looks related to this fix: https://github.com/liferay/liferay-portal/commit/446a7995e74512811226daef127d54c3eb567024

**Comment by jrodbx** [comment]
Latest update: https://github.com/petershin/liferay-portal/pull/546#issuecomment-503627406

**Comment by jrodbx** [comment]
Merged in https://github.com/brianchandotcom/liferay-portal/pull/74821#issuecomment-504505057

**Comment by holatuwol** [comment]
ci:close

**Comment by holatuwol** [comment]
@jrodbx : Thanks for the updates and the code contribution!

**Comment by oldergod** [comment]
kudos @jrodbx !!

**Pull request closed without merging**
