### PR TITLE
LPS-169351 Fix broken Learn more link in the Category Facet's Configuration screen

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-169351

### CODE REVIEW

**Comment by lipusz** [comment]
ci:forward

**Comment by thektan** [comment]
I noticed no ci activity on this ticket so I'm going to attempt to forward this on another PR through the liferay-search repo. https://github.com/liferay-search/liferay-portal/pull/681

**Comment by thektan** [comment]
ci:close

**Comment by lipusz** [comment]
Damn... Thanks @thektan for catching it. GitHub tricked me, didn't notice it wasn't liferay-search 😝

**Pull request closed without merging**
