### PR TITLE
Fix wrong French translation for "Look and feel configuration"

### PR DESCRIPTION
**Pull request by BenjaminBini**
"Look and feel" can be translated into "apparence" but never into "apparence and sentiments" (sentiments = feelings).

### CODE REVIEW

**Comment by sammonsjl** [comment]
In an effort to clean up our liferay-portal repository we are currently going through all old pull requests and closing them.  If you feel this change is still necessary please reopen the pull request and we can assist you.

**Comment by sammonsjl** [comment]
ci:close

**Comment by BenjaminBini** [comment]
This one is still relevant.

**Comment by BenjaminBini** [comment]
ci:open

**Comment by BenjaminBini** [comment]
(Don't know if it works)

**Comment by sammonsjl** [comment]
ci:open

**Comment by sammonsjl** [comment]
ci:reopen

**Comment by sammonsjl** [comment]
In order to move this forward we need you to create a ticket in JIRA and respond to the Contributor License Agreement by clicking the Contribute Solution button.  You can then use this same ticket in the future to show that you accepted the agreement when you submit pull requests.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
