### PR TITLE
LPS-68104 Update the com-liferay-journal repository

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest @pyoo47 what's happening here? @shuyangzhou is this a real bug with Julio's code?

**Comment by shuyangzhou** [comment]
Yeah, it is a real issue.
```
     [exec] 12:25:56,837 WARN  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][org_apache_felix_fileinstall:103] Error while starting bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.journal.terms.of.use.jar 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.journal.terms.of.use [310]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.util; version="[7.0.0,7.1.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)
     [exec] 12:25:56,838 ERROR [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][org_apache_felix_fileinstall:112] Exiting the JVM 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.journal.terms.of.use [310]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.util; version="[7.0.0,7.1.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)
```

CC @juliocamarero

**Comment by pyoo47** [comment]
@brianchandotcom It's throwing this exception during portal startup. Since this is not happening on other liferay-portal pulls and it's a journal module I am guessing that either something is wrong in the journal subrepo or there's some corresponding change that needs to be made in portal that hasn't been done yet?

```
     [exec] 12:29:26,964 ERROR [localhost-startStop-1][ModuleFrameworkImpl:1440] Unable to start bundle com.liferay.journal.terms.of.use
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.journal.terms.of.use [311]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.util; version="[7.0.0,7.1.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1437)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:414)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:99)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:253)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
```

**Pull request closed without merging**
