### PR TITLE
LPS-67339 Update the com-liferay-journal repository

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:merge

**Comment by juliocamarero** [comment]
👏 👏 👏 👏 👏 👏 👏  It worked!!!! 😄

**Comment by pyoo47** [comment]
Woo Hoo!!!

**Comment by brianchandotcom** [comment]
Wow @juliocamarero we had our first!!!!!!

**Comment by juliocamarero** [comment]
Thanks a lot for your effort!!!! @brianchandotcom @pyoo47 @stsquared99 👏 👏 👏 👏

**Pull request closed without merging**
