### PR TITLE
concurrence problem on PortletResponseImpl.java

### PR DESCRIPTION
**Pull request by LinoOscar**
Hi friends

I have one environment of a lof of portlets, aproximately 20 in one page. All of them use a own architecture that uses ofter the method public void addProperty(String key, Element element)  from this class. Sometimes, I lost any of this elements.

I synchronize for all instances of this class method transferMarkupHeadElements() supossing next scnary:

-> Thread 1 read request; MARKUP_HEAD_ELEMENT is null: thread 1 set this key to new ArrayList<>();
-> Thread 2 read request: thread1 still not add any element ot list... then, thread2 read null 
-> Thread 1 just add first element to  MARKUP_HEAD_ELEMENT 
-> Thread 2 put again  MARKUP_HEAD_ELEMENT  to new ArrayList, losing this first add made on Thread1

From the moment that i add this sunchronized to my version, my problem was solved (no fails in my stress tests)

### CODE REVIEW

**Comment by sammonsjl** [comment]
Hi @LinoOscar thank you for the contribution!

/Cc @holatuwol @jonathanmccann @SamZiemer @AngeloJ can one you take a look at this one?

**Comment by holatuwol** [comment]
@sammonsjl : Double-checking. There isn't an LPS ticket so we have no idea how to know, but has @LinoOscar accepted the Liferay contributor agreement? I don't think we formally identified a way to determine that just from GitHub, and an LPS ticket was previously the only way for us to know for sure.

**Comment by sammonsjl** [comment]
@holatuwol Currently an LPS ticket is the only way to accept it.  We (Developer Relations) are working on a new process that doesn't involve JIRA but it's still in the works.

@LinoOscar if you haven't already done so can you create a ticket and accept the contributor agreement and post a link in this pull request?

**Comment by holatuwol** [comment]
@LinoOscar : In case there's any confusion about what Jamie is saying, please read through the JIRA section of the contributor's guide.

https://github.com/liferay/liferay-portal/blob/master/CONTRIBUTING.markdown#jira

**Comment by sammonsjl** [comment]
Closing due to inactivity.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
