### PR TITLE
LRQA-29747 Update the com-liferay-journal repository

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:merge

**Comment by stsquared99** [comment]
Hi guys, Brian asked me to suspend all subrepo operations for the time being, we'll probably turn it back on in a few hours. I will keep you posted.
Thanks

**Comment by ealonso** [comment]
Hey @stsquared99,

Are the subrepo operations working again??

Thanks!!!

**Comment by ealonso** [comment]
ci:merge

**Comment by stsquared99** [comment]
Hi Eudaldo, Brian still hasn't allowed me to enable it yet. I will check again today. Sorry for the inconvenience.
Thanks

**Comment by stsquared99** [comment]
Hi Eudaldo, subrepo commands have been re-enabled. Thanks for your patience.

**Comment by ealonso** [comment]
@stsquared99 Thanks!!!!

**Comment by ealonso** [comment]
ci:merge

**Pull request closed without merging**
