### PR TITLE
 LPD-22974 Clause Contributors configurations are stored in Blueprints in a less verbose way and with improved consistency when it comes to the handle of new contributors introduced to the system

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPD-22974

**Subtasks:** 
https://liferay.atlassian.net/browse/LPD-26515
https://liferay.atlassian.net/browse/LPD-26521
https://liferay.atlassian.net/browse/LPD-26507

**Authors:** @joshuacords @oliv-yu

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
@joshuacords nice! did you want to send to liferay-search? 😅

**Comment by joshuacords** [comment]
@oliv-yu - Ah dang it - I always miss this, or I refresh and it reverts to the original target repository.

You know what let's just force it in! 
JK

**Pull request closed without merging**
