### PR TITLE
LPS-75174 Update the repository com-liferay-analytics

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @brianchandotcom 

this is the first merge request for the Analytics repo.

thank you!

### CODE REVIEW

**Comment by jpince** [comment]
ci:merge

**Comment by jpince** [comment]
@stsquared99 can CI send pulls from this sub repo automatically? Or is that enabled now that this first merge is complete? Thanks!

**Comment by jpince** [comment]
@Ithildir if you have time, can you please provide a quick review of https://github.com/liferay/liferay-portal/compare/2ad572a9d29d0ea47fdd5946d6b763b80187a34b...88ac0c4324dd69b06e7788dc366e8927a8ff6136 so make sure this initial merge didn't miss anything? Thanks!

**Comment by stsquared99** [comment]
@jpince I've turned on autopull for this subrepo.
Thanks

**Comment by Ithildir** [comment]
@jpince, LGTM! 😊

**Comment by jpince** [comment]
@Ithildir I had to look that one up, lol. Thanks for the review!

**Pull request closed without merging**
