### PR TITLE
COMMERCE-2623 Added possibility to remove all order items from CommerceOrderContentPortlet

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
image

As per screenshot, added the "Remove All Items" action item remove all of the order items, though leaving the order intact.

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by sammonsjl** [comment]
Cleaning up old prs on the main repo.  Please re-open if still needed.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
