### PR TITLE
LPS-166501 fixed management bar tooltip message

### PR DESCRIPTION
**Pull request by JMachado98**
Issue Link: https://issues.liferay.com/browse/LPS-166501

The issue was, when hover the mouse over order list buttom a Tooltip appears with text "Reverse Sort Direction". Fixed to display the correct text "Reverse Order Direction".

### CODE REVIEW

**Comment by JMachado98** [comment]
@kevenleone Can you review this PR please?

**Comment by kevenleone** [comment]
LGTM @JMachado98

**Comment by kevenleone** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:frontend

**Comment by kevenleone** [comment]
Pull Request forwarded: https://github.com/brianchandotcom/liferay-portal/pull/125918

**Comment by kevenleone** [comment]
ci:close

**Pull request closed without merging**
