### PR TITLE
LPS-85235 test revert | master

### PR DESCRIPTION
**Pull request by jpince**
Revert state to before https://github.com/brianchandotcom/liferay-portal/pull/64547. Expect tests to pass

DDMFormInstanceStagedModelDataHandlerTest.testCleanStagedModelDataHandler
DLFileEntryTypeStagedModelDataHandlerTest.testCleanStagedModelDataHandler
FileEntryStagedModelDataHandlerTest.testCleanStagedModelDataHandler
FolderStagedModelDataHandlerTest.testCleanStagedModelDataHandler

StructuredContentNestedCollectionResourceFilteringTest.testGetPageItemsFilterByStructureField - this test is consistently failing now

StructuredContentNestedCollectionResourceFilteringTest.testGetPageItemsFilterByTitleContains Consistently fails in Sybase ONLY

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:c86937909e87840f7371b7685ac7a1ff7b046148

**Comment by jpince** [comment]
ci:test:39d01ca3357e9930c80bff14533aa872123af7f1

**Comment by yichenroy** [comment]
ci:test:39d01ca3357e9930c80bff14533aa872123af7f1

**Comment by jpince** [comment]
resent to jpince: https://github.com/jpince/liferay-portal/pull/85

**Pull request closed without merging**
