### PR TITLE
LPS-89415 Do not include portal-vulcan in FP builds yet

### PR DESCRIPTION
**Pull request by ethanbustad**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
Looks like this was released when GA1 released, but it's somehow not included in the Liferay bundle even though the app.bnd suggests it should included (and it's included in nightly snapshot builds, even though that's supposed to mirror the Liferay release process).

https://github.com/liferay/liferay-portal/blob/7.2.0-ga1/modules/.releng/apps/portal-vulcan/app.changelog

**Comment by nicolelau** [comment]
@holatuwol Do you mean 7.2 GA1 or 7.1? I see the modules inside of my DXP 7.2 GA1 and 7.2 CE GA1 bundles. This commit was intended to exclude it from 7.1 FPs for now.

**Comment by holatuwol** [comment]
@nicolelau : I meant 7.2, but I was looking for the wrong name. It's called "Liferay CE Foundation - Liferay Portal CE Vulcan" but I was looking for something named "Liferay Portal Vulcan" instead.

**Comment by holatuwol** [comment]
Looks like we committed and reverted on 7.1.x branch:

* https://github.com/liferay/liferay-portal/commit/13b2a88b228ffede7ea1c94bae3a3938fc9e4af8
* https://github.com/liferay/liferay-portal/commit/c2cad2b111bfc2f7afb1ef9237edaa351a84f268

**Comment by holatuwol** [comment]
ci:close

**Pull request closed without merging**
