### PR TITLE
LPS-110508 Open in full view

### PR DESCRIPTION
**Pull request by balazssk**
Hi @dacousalr ,

Changed the Web Content Display's View History icon to open in full view instead of a poup.

Can you please review?
https://issues.liferay.com/browse/LPS-110508

Thanks,
Balázs

### CODE REVIEW

**Comment by dacousalr** [comment]
Hi @balazssk,

It seems that this PR has been sent to the wrong repo. Could you resend it?

Thanks in advance

**Comment by balazssk** [comment]
Hi @dacousalr ,
Shouldn't I update master before sending this fix to 7.2.x?

**Comment by dacousalr** [comment]
Sorry, I meant this PR was sent to the wrong user.

Please send it to my user.

Thanks

**Comment by balazssk** [comment]
O, sorry about that

**Pull request closed without merging**
