### PR TITLE
Automated Test - COMMERCE-6193| master

### PR DESCRIPTION
**Pull request by wesleyroberts**
liferay-branch

### CODE REVIEW

**Comment by wesleyroberts** [comment]
https://issues.liferay.com/browse/COMMERCE-6193 ; cc: @lorenzolapescara

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by wesleyroberts** [comment]
https://issues.liferay.com/browse/COMMERCE-6193; cc: @lorenzolapescara

**Comment by kristinonias** [comment]
@wesleyroberts 

This pull request was sent to the wrong user. Please close this PR and send to liferay-commerce user.

**Comment by wesleyroberts** [comment]
I'm sorry.

**Pull request closed without merging**
