### PR TITLE
Line 170 should use startsWith() to match line 172

### PR DESCRIPTION
**Pull request by mcgitty**
Line 172 path.substring(contextPath.length()) only extract from the beginning of the string, no in the middle, which could happen if line 170 is path.startsWith(contextPath).

### CODE REVIEW

**Comment by sammonsjl** [comment]
@mcgitty thank you very much for the contribution and rebasing it on master for us!

 @holatuwol @jonathanmccann @SamZiemer @AngeloJ can one you take a look at this one?

Note: CLA accepted here: https://issues.liferay.com/browse/LPS-68424

**Comment by holatuwol** [comment]
Filed under [LPS-114767](https://issues.liferay.com/browse/LPS-114767).

**Comment by holatuwol** [comment]
https://github.com/jonathanmccann/liferay-portal/pull/1843

**Comment by mcgitty** [comment]
Superseded by [a08dfd1a50...78111dc140](https://github.com/brianchandotcom/liferay-portal/compare/a08dfd1a50...78111dc140).

**Pull request closed without merging**
