### PR TITLE
LPS-55332 Update the com-liferay-journal repository

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @juangon

**Comment by brianchandotcom** [comment]
@shuyangzhou see these broken tests? Just the ones for modules-integration-oracle-*

I know about the them porygon one, it's a missing resource in our local mirrors.

Can you let me know if the oracle one is real?

**Comment by shuyangzhou** [comment]
It is a arquillian broken connection failure, it has been happening for a while for whatever reason it is, but not caused by this pull. This is going to be an issue though, due to we have no way to change their inner code.

**Comment by brianchandotcom** [comment]
@shuyangzhou can we add a retry? or wrap their logic for a retry?

**Comment by shuyangzhou** [comment]
@brianchandotcom We can not, it is deep inside arquillian code, it is their jmx connections, from client to server, we have no access to or no way to know how to retry.

**Comment by brianchandotcom** [comment]
ci:merge:force

**Comment by brianchandotcom** [comment]
ci:merge:force

**Pull request closed without merging**
