### PR TITLE
LPS-122725 fix input-date prefilling on mobile

### PR DESCRIPTION
**Pull request by dbagrey**
https://issues.liferay.com/browse/LPS-122725 

**Problem overview:**
liferay-ui: input-date is pre-filled when viewed from a mobile device

**Steps to Reproduce:**
- Place the liferay-ui: input-date tag with an empty value on the jsp page
- Deploy portlet with jsp page
- Open page with portlet on a mobile device

**Expected Results:**
Input contain empty value

**Actual Results:**
input is prefilled

### CODE REVIEW

**Comment by dgomezg** [comment]
Thank you @dbagrey dbagrey for your contribution.

 But it's better if you send the PR to https://github.com/liferay-frontend/liferay-portal so that the Frontend Infra team can review and merge it.

Can you please forward the PR to that repo?

**Comment by dbagrey** [comment]
Thanks @dgomezg. Forwarded to [453](https://github.com/liferay-frontend/liferay-portal/pull/453)

**Comment by wincent** [comment]
ci:close

**Comment by sammonsjl** [comment]
ci:open

**Pull request closed without merging**
