### PR TITLE
Es2015 demo

### PR DESCRIPTION
**Pull request by luscicli**

### CODE REVIEW

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by mwilliams2014** [comment]
@sez11a Recommending this pull be closed as working ES2015 examples and information can be found here: https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/using-es2015-in-your-portlets

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
