### PR TITLE
LPS-110422 Gradle plugins not compatible with gradle 6.0+

### PR DESCRIPTION
**Pull request by damien-abos**
for Gradle 6 compatibility

### CODE REVIEW

**Comment by juddgaddie** [comment]
Is there any reason why this should not be merged ?

**Comment by wincent** [comment]
> Is there any reason why this should not be merged ?

In practice, pulls need to go to [be sent to brianchandotcom's fork](https://github.com/brianchandotcom/liferay-portal/pulls), not this one. (He merges the commits to his fork, and that `master` branch gets periodically, automatically synced over here).

**Comment by damien-abos** [comment]
@wincent, I've create a jira account to create a bug, I have done my best to contribute. And no feedback since...
There is no clear process in liferay community : it's a shame !

**Comment by wincent** [comment]
> @wincent, I've create a jira account to create a bug, I have done my best to contribute. And no feedback since...
> There is no clear process in liferay community : it's a shame !

Sorry to hear about your experience, @damien-abos. FWIW, we're already aware of some of the barriers to contributing, but it's still useful to hear feedback like this. (And I'll mention @JorgeFerrer, Liferay's VP of Engineering, here, because I know this is a subject that he has been monitoring.)

**Comment by JorgeFerrer** [comment]
Hey @damien-abos ,

I'm really sorry that you've had such a bad experience trying to contribute. We are aware that we need to continue investing in improving it.
The process itself is documented at https://portal.liferay.dev/participate/feedback/overview and in particular here: https://portal.liferay.dev/participate/fix-a-bug/overview
As you can see, you have actually done the right thing sending the pull here. We have recently had some changes in the team responsible for monitoring these pulls and it seems your (and possibly some others) have not been noticed. I'll bring it up to them.
Please keep the contributions coming and feel free to mention me directly when you don't hear back after a reasonable period.

**Comment by dgomezg** [comment]
@petershin could you please take a look at this PR?

**Comment by petershin** [comment]
@dgomezg - Forwarded the pull to review the changes https://github.com/petershin/liferay-portal/pull/984

**Comment by juddgaddie** [comment]
@JorgeFerrer for what its worth as much as you can keep everything in Github the easier it will be for people to contribute, Pull Requests at least and issues would be even better.

**Pull request closed without merging**
