### PR TITLE
Update Language_fi.properties

### PR DESCRIPTION
**Pull request by tykkala**
Fixed one misspelled word and two totally wrong meanings.

### CODE REVIEW

**Comment by sammonsjl** [comment]
Hi @tykkala thank you for the contribution!

/Cc @holatuwol @jonathanmccann @SamZiemer @AngeloJ can one you take a look at this one?

**Comment by holatuwol** [comment]
@tykkala , @sammonsjl : Translations would be added to CrowdIn.

https://crowdin.com/project/liferay-portal/fi

**Comment by sammonsjl** [comment]
@holatuwol I should have know that.  
@tykkala would please use CrowdIn for submitted a translation?  Details for CrowdIn can be found here: https://portal.liferay.dev/participate/translate/overview

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
