### PR TITLE
Update Language_cs.properties

### PR DESCRIPTION
**Pull request by m-czernek**
The words were exactly opposite. "Rate this as good" said "I don't like" and "Rate this as bad" said "I like". I also changed it to make it more idiomatic.

### CODE REVIEW

**Comment by m-czernek** [comment]
@sammonsjl I correct your translation which is still exactly the opposite (i.e. "I don't like" translated as "I like" and vice versa). Do you think this is no longer necessary? The language didn't change in the meantime. I will not reopen, it's obvious Liferay does not care for contributions from the community.

**Comment by sammonsjl** [comment]
@m-czernek I will be the first to admit we have been terrible at accepting contributions from the community.  In an effort to improve things I was trying to go through and clean out things that were possibly either: already committed elsewhere or were out of date.  Please accept my apology for the misunderstanding and I'll be happy to reopen the request for you.

**Comment by sammonsjl** [comment]
ci:reopen

**Comment by sammonsjl** [comment]
In order to move this forward we need you to create a ticket in JIRA (issues.liferay.com) and respond to the Contributor License Agreement by clicking the Contribute Solution button. You can then use this same ticket in the future to show that you accepted the agreement when you submit pull requests.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
