### PR TITLE
[TS] LPS-122231 portal-search-web: increase to full span when facet menu i…

### PR DESCRIPTION
**Pull request by joshuacords**
…s absent

https://issues.liferay.com/browse/LPS-122231
https://issues.liferay.com/browse/LPP-39156

LPS-122231 Search Widget doesn't span width when Facets are hidden

Author: @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant:norebase

**Comment by joshuacords** [comment]
ci:test:stop

**Comment by joshuacords** [comment]
ci:test:sf:norebase

**Comment by joshuacords** [comment]
ci:test:relevant:norebase

**Comment by joshuacords** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
@joshuacords I guess you wanted to submit this to the `liferay-search` user, not to "liferay".

**Pull request closed without merging**
