### PR TITLE
6.2.x

### PR DESCRIPTION
**Pull request by alessandro-aglietti**
We encountered a redirect loop caused by a reverse proxy bad configuration: request.isSecure() still return false because on the Tomcat connector configuration had not been set "secure=true".

To troubleshoot we were forced to hook LoginAction to add some debug information.

It'll useful to have debug log!

### CODE REVIEW

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by sammonsjl** [comment]
In an effort to clean up our liferay-portal repository we are currently going through all old pull requests and closing them.  If you feel this change is still necessary please reopen the pull request and we can assist you.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
