### PR TITLE
fix NPE

### PR DESCRIPTION
**Pull request by bill2004158**
pollerRequest will be null if "Poller processor not found for portlet"
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/poller/PollerRequestHandlerImpl.java#L167

### CODE REVIEW

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by sammonsjl** [comment]
In an effort to clean up our liferay-portal repository we are currently going through all old pull requests and closing them.  If you feel this change is still necessary please reopen the pull request and we can assist you.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
