### PR TITLE
LPD-33798 Remove 'emails' from the Claims because it does not arrive at all

### PR DESCRIPTION
**Pull request by tomibiro**

### CODE REVIEW

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:close

**Comment by stian-sigvartsen** [comment]
Closed the PR because it was sent to the wrong fork. Should go to liferay-appsec

**Comment by tomibiro** [comment]
I opened the new pr: https://github.com/liferay-appsec/liferay-portal/pull/1939

**Pull request closed without merging**
