### PR TITLE
fix eclipse errors on build

### PR DESCRIPTION
**Pull request by zhaiyz**
There are no 'lib/portal/oauth.jar' and 'lib/portal/oauth-provider.jar' in branch 6.1.x, and not 'portal-web/test' but 'portal-web/test/functional' is in the build path.

### CODE REVIEW

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by sammonsjl** [comment]
In an effort to clean up our liferay-portal repository we are currently going through all old pull requests and closing them.  If you feel this change is still necessary please reopen the pull request and we can assist you.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
