### PR TITLE
LPS-67973 Update the com-liferay-journal repository

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:merge

**Comment by juliocamarero** [comment]
@stsquared99 do you know what does this error mean?

thank you!

**Comment by jhendley** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@jhendley @anthony-chu are these failures real?

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@brianchandotcom @michaelhashimoto I don't think these test failures are related to my pull...

**Comment by juliocamarero** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@juliocamarero The Poshi test failures are caused by the commit that was merged here: brianchandotcom#43044.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
New pull request here: https://github.com/liferay/liferay-portal/pull/1020

**Pull request closed without merging**
