### PR TITLE
[LPS-55955] added new property rss.feed.refresh.time

### PR DESCRIPTION
**Pull request by sjsmit**
[LPS-55955] added new property rss.feed.refresh.time(default 20) + used it in RSSWebCacheItem so users can set the refresh time of rss feeds instead of the hardcode 20 minutes.

### CODE REVIEW

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by MartVisser** [comment]
Can one of the admins verify this patch?

**Comment by sammonsjl** [comment]
In an effort to clean up our liferay-portal repository we are currently going through all old pull requests and closing them.  If you feel this change is still necessary please reopen the pull request and we can assist you.

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
