### PR TITLE
Javadoc: GetterUtil class

### PR DESCRIPTION
**Pull request by slemarchand**
@codyhoag

### CODE REVIEW

**Comment by codyhoag** [comment]
Reviewed and sent JorgeFerrer#769 for SME review. You may now close this pull request. Thanks for your patience!

**Comment by codyhoag** [comment]
@slemarchand This was merged into upstream in brianchandotcom#42848. Thanks again! :sunglasses:

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by inacionery** [comment]
Can one of the admins verify this patch?

**Comment by sammonsjl** [comment]
ci:close

**Pull request closed without merging**
